/* Generated by brand-lab/tools/objects.cjs. Do not edit by hand. */

/** Intrinsic size of each object at 960w, for layout-stable images. */
export const OBJECTS = {
  "bubble": { width: 960, height: 783 },
  "heart": { width: 960, height: 860 },
  "bookmark": { width: 960, height: 1293 },
  "share": { width: 960, height: 969 },
  "bell": { width: 960, height: 1059 },
  "bubble-deflated": { width: 960, height: 635 },
  "bell-deflated": { width: 960, height: 860 },
  "bookmark-deflated": { width: 960, height: 1229 },
  "bubble-popped": { width: 960, height: 529 },
} as const;

export type ObjectName = keyof typeof OBJECTS;
